### PR TITLE
Fix IT sample global volume and sample vibrato.

### LINKED ISSUE #102: .it global sample volume is broken
This .it file contains two copies of the same sample with different global sample volumes that are played at different pitches.  When played in Impulse Tracker, one low sample can be heard clearly; when it's played with xmp, both samples can be heard equally loud.  libxmp seems to treat the global sample volume as maximum.

[global_sample_volume.it.zip](https://github.com/cmatsuoka/libxmp/files/1220272/global_sample_volume.it.zip)

### PR DESCRIPTION
**Pull request by AliceLR**
Fixes a few bugs in IT sample global volume and sample vibrato handling:

* IT sample global volume was being ignored in sample mode due to `QUIRK_INSVOL` not being enabled. `QUIRK_INSVOL` is now unconditionally enabled for IT modules.
* IT sample global volume was also being ignored in instrument mode for IT 1.x modules due to `QUIRK_INSVOL` not being enabled for IT 1.x modules.
* Fixed an incorrect bitshift on IT sample vibrato depth that resulted in IT sample vibrato being very weak.
* Sample vibrato rate is now rounded instead of truncated in read_event.c. This is a bandaid fix and the LFO period size should probably eventually be expanded.

Fixes #102 and #103.

edit: 5 failing tests from this patch, will look into them.

### CODE REVIEW

**Comment by AliceLR** [comment]
I fixed the one module data test that this broke (differences were due to the change in sample vibrato depth). Haven't looked too close at the four failing OpenMPT mixer tests yet.

**Comment by AliceLR** [comment]
Remaining tests:
* `test_openmpt_it_autovibrato_reset.c`: the property it is testing (the sample vibrato sweep) is unaffected by these changes, so I've just updated the data file.
* `test_openmpt_it_filter_reset.c`: ditto (testing filter macros, changes are due to the sample global volume fix).
* `test_openmpt_it_panreset.c`: ditto (testing `X80`, changes are due to sample global volume fix).
* `test_openmpt_it_samplenumberchange.c`: ditto (testing sample numbers without notes, changes are due to sample global volume fix).

**Comment by sezero** [comment]
Let's have @sagamusix and @cmatsuoka look at this.

**Review by cmatsuoka — APPROVED** [review]
IT support in libxmp is generally innacurate and problems are fixed as they're reported, so if this change fixes issues or makes replay sound "less wrong" it should be good to go. (There are many hacks in IT replaying caused by IT support being added after the common replay code was already in place -- in the future we should refactor the common player to be more IT friendly, including adding proper bidirectional sample  loops).

**Comment by AliceLR** [comment]
One of the tests on the master branch failed after this was merged: https://travis-ci.org/github/libxmp/libxmp/builds/743831472

I did a local build of libxmp and the tests on my iMac with GCC with no issue so that's not the problem. Is this maybe an issue on Travis' end?

**Comment by sezero** [comment]
> One of the tests on the master branch failed after this was merged: https://travis-ci.org/github/libxmp/libxmp/builds/743831472
> 
> I did a local build of libxmp and the tests on my iMac with GCC with no issue so that's not the problem. Is this maybe an issue on Travis' end?

Seems like it

**Pull request merged**
