### PR TITLE
Allow xmp_smix_play_* to play key off, cut, and fade events.

### LINKED ISSUE #106: Unable to Cut Looped SMIX Instrument
```c
xmp_smix_play_instrument(ctx, 3,          60, 0, 0); // Instrument #3 contains a loop.
sleep(10);
xmp_smix_play_instrument(ctx, 3, XMP_KEY_CUT, 0, 0);
```

The above code does not work as expected, as pitches passed to `xmp_smix_play_instrument` are incremented by one.  Currently, there is no clean way to cut a looped instrument.  (If I am wrong, please let me know!)

### PR DESCRIPTION
**Pull request by AliceLR**
Fixes #106. This needs better testing and is probably not 100% correct currently.

### CODE REVIEW

**Comment by AliceLR** [comment]
After some testing against my modified xmp-cli and a few tweaks, this works now roughly as it ought to. Marking this ready for review.

**Comment by sezero** [comment]
This patch does not apply cleanly anymore - needs a rebase.

PING @cmatsuoka for review?

**Review by sezero — APPROVED** [review]
This is OK by me. If @cmatsuoka and/or @NoSuck doesn't respond, we can merge after about a week.

**Review by cmatsuoka — APPROVED** [review]
The smix_* calls are pretty much a bonus feature that don't (or shouldn't) affect module replaying, so it adding functionality there should be harmless.

**Comment by sezero** [comment]
OK then, let's get this in.

**Pull request merged**
