### PR TITLE
Fix test-dev sample, depack, prowizard, and api leaks.

### PR DESCRIPTION
**Pull request by AliceLR**
First of many. Fixes any trivial leaks in the test_sample_\*, test_depack_\*, test_prowizard_\*, and test_api_\* test files. There are some test_api_* leaks that this doesn't fix (see #110) but since those may be actual bugs they should probably be handled separately.

### CODE REVIEW

**Comment by AliceLR** [comment]
Looking into why this happened a few times...:
```
test 22: test_sample_load_delta: at test_sample_load_delta.c:24: Invalid 8-bit conversion: **fail**
test 23: test_sample_load_signal: at test_sample_load_signal.c:32: Invalid 8-bit conversion: **fail**
```

**Comment by AliceLR** [comment]
So that's why those were static! Oof... :(

**Comment by sezero** [comment]
Personally I don't like those `free(s.data - 4)`.  We need something,
say libxmp_free_sample() or free_sample_data() for this. Even a macro
would do.  That way, if internals ever change the users of this macro
won't be affected.

**Comment by AliceLR** [comment]
Yeah, I'm not a fan of those either.

**Comment by AliceLR** [comment]
Updated to add a `libxmp_free_sample` function. I've updated src/load.c and src/smix.c to use the new function instead of the same `data - 4` hack.

**Review by sezero — APPROVED** [review]
This is OK.

**Pull request merged**
