### PR TITLE
Fix NoteOffInstr.it note off volume bugs.

### PR DESCRIPTION
**Pull request by AliceLR**
Fixes two bugs related to note off and volume handling both found in NoteOffInstr.it (and in a couple of places in atomic_playboy.it: #145):

* Lines with both an instrument and a note off should allow the instrument volume to be used. Fixes row 4, channel 1.
* Volume events should not be ignored on a line with a note off. Fixes row 4, channel 2.

### CODE REVIEW

**Comment by sezero** [comment]
@sagamusix, @cmatsuoka ?

**Comment by sezero** [comment]
PING @sagamusix, @cmatsuoka ?

**Comment by sagamusix** [comment]
Sorry, I currently don't really have the time to dive deep into the xmp replayer to understand if the fix is correct. If it plays the test case correctly, feel free to approve it!

**Review by sezero — APPROVED** [review]
> If it plays the test case correctly, feel free to approve it

I assume @AliceLR done thorough play-testing. Approving.

**Review by cmatsuoka — APPROVED** [review]
As I mentioned before, the existing implementation grew organically based on trial and error which causes the IT replay to be flawed in many aspects. To fix some of the problems we need structural changes (such as rewriting bidirectional sample processing since unrolling them beforehand doesn't work for sustain loops), but other problems can be addressed using simple yet functional fixes like this one. Generally, if we can fix existing problems without introducing regressions or increasing architectural chaos, I'm all for it.

**Pull request merged**
