### PR TITLE
Fix out-of-bounds read in IT loader caused by invalid effects.

### LINKED ISSUE #246: Single-byte global buffer over-read when loading some IT / MPTM files...
I noticed significant commit activity over the past few weeks, so I thought I'd take the version for another short drive before the 4.5.0 release is produced - at least load several hundred modules and listen to several of them :)

My AddressSanitizer-instrumented build of libxmp commit ID 604832e52fce256b14fea1f151a535980c41373c aborts because of a single-byte global buffer over-read (not dangerous, but still) when loading several files by Saga Musix, downloaded from http://sagamusix.de/en/music/ , e.g. Rainforest and Logical Control Right:

```
Loading rainforest.it (36 of 55)
=================================================================
==1719424==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7fe8a6dca71c at pc 0x7fe8a6c941e2 bp 0x7ffd473197d0 sp 0x7ffd473197c8
READ of size 1 at 0x7fe8a6dca71c thread T0
    #0 0x7fe8a6c941e1 in xlat_fx .../xmp/libxmp/src/loaders/it_load.c:98:19
    #1 0x7fe8a6c941e1 in load_it_pattern .../xmp/libxmp/src/loaders/it_load.c:981:5
    #2 0x7fe8a6c941e1 in it_load .../xmp/libxmp/src/loaders/it_load.c:1291:7
    #3 0x7fe8a6c3f1e4 in load_module .../xmp/libxmp/src/load.c:461:18
    #4 0x7fe8a6c3e60c in xmp_load_module .../xmp/libxmp/src/load.c:606:8
    #5 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #6 0x7fe8a6758cc9 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x420679 in _start (.../bin/xmp+0x420679)

0x7fe8a6dca71c is located 1 bytes to the right of global variable 'fx' defined in 'src/loaders/it_load.c:59:20' (0x7fe8a6dca700) of size 27
SUMMARY: AddressSanitizer: global-buffer-overflow .../xmp/libxmp/src/loaders/it_load.c:98:19 in xlat_fx
Shadow bytes around the buggy address:
  0x0ffd94db1490: 00 00 00 f9 f9 f9 f9 f9 00 05 f9 f9 f9 f9 f9 f9
  0x0ffd94db14a0: 00 01 f9 f9 f9 f9 f9 f9 00 07 f9 f9 f9 f9 f9 f9
  0x0ffd94db14b0: 00 00 f9 f9 f9 f9 f9 f9 00 03 f9 f9 f9 f9 f9 f9
  0x0ffd94db14c0: 00 00 04 f9 f9 f9 f9 f9 00 06 f9 f9 f9 f9 f9 f9
  0x0ffd94db14d0: 00 04 f9 f9 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
=>0x0ffd94db14e0: 00 00 00[03]f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0ffd94db14f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd94db1500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd94db1510: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd94db1520: 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9 00 01 f9 f9
  0x0ffd94db1530: f9 f9 f9 f9 00 01 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1719424==ABORTING
```

These files used to load with a build of libxmp b41dc4c963fa2084b715faeb8845a6ba9b7c91c4 from early November, but my previous build probably wasn't AddressSanitizer-instrumented because I think I forgot, so this piece of information probably isn't worth much for debugging and fixing the issue.

### PR DESCRIPTION
**Pull request by AliceLR**
The IT loader bounds effects values from 0 to 31 but the effect translation table is shorter than that. Some IT modules use non-standard effects that were reading this array out of bounds. This patch just extends the array to size 32 (in the off chance these ever get supported...). Fixes #246.

### CODE REVIEW

**Review by sezero — APPROVED** [review]
Will merge as soon as Travis completes.

**Comment by debrouxl** [comment]
BTW, I see similar constructs in several other loaders:
```
src/loaders/no_load.c:82:static const uint8 fx[] = {
src/loaders/no_load.c:236:                                      event->fxt = fx[fxt];
src/loaders/okt_load.c:68:static const int fx[] = {
src/loaders/okt_load.c:266:             e->fxt = fx[fxt];
src/loaders/s3m_load.c:116:static const uint8 fx[] = {
src/loaders/s3m_load.c:157:     switch (e->fxt = fx[e->fxt]) {
src/loaders/it_load.c:59:static const uint8 fx[] = {
src/loaders/it_load.c:103:      switch (e->fxt = fx[e->fxt]) {
src/loaders/669_load.c:83:static const uint8 fx[] = {
src/loaders/669_load.c:232:             event->fxt = fx[MSN(ev[2])];
src/loaders/far_load.c:104:static const uint8 fx[] = {
src/loaders/far_load.c:237:         event->fxt = fx[MSN(fxb)];
src/loaders/stm_load.c:128:static const uint8 fx[16] = {
src/loaders/stm_load.c:335:                             event->fxt = fx[LSN(b)];
src/loaders/imf_load.c:132:static const uint8 fx[] = {
src/loaders/imf_load.c:177:    switch (*fxt = fx[*fxt]) {
src/loaders/liq_load.c:116:static const uint8 fx[] = {
src/loaders/liq_load.c:150:    switch (e->fxt = fx[e->fxt]) {
src/loaders/stx_load.c:118:static const uint8 fx[] = {
src/loaders/stx_load.c:338:                                     event->fxt = fx[t];
```

**Comment by sezero** [comment]
> BTW, I see similar constructs in several other loaders:
> 
> ```
> src/loaders/no_load.c:82:static const uint8 fx[] = {
> src/loaders/no_load.c:236:                                      event->fxt = fx[fxt];
> src/loaders/okt_load.c:68:static const int fx[] = {
> src/loaders/okt_load.c:266:             e->fxt = fx[fxt];
> src/loaders/s3m_load.c:116:static const uint8 fx[] = {
> src/loaders/s3m_load.c:157:     switch (e->fxt = fx[e->fxt]) {
> src/loaders/it_load.c:59:static const uint8 fx[] = {
> src/loaders/it_load.c:103:      switch (e->fxt = fx[e->fxt]) {
> src/loaders/669_load.c:83:static const uint8 fx[] = {
> src/loaders/669_load.c:232:             event->fxt = fx[MSN(ev[2])];
> src/loaders/far_load.c:104:static const uint8 fx[] = {
> src/loaders/far_load.c:237:         event->fxt = fx[MSN(fxb)];
> src/loaders/stm_load.c:128:static const uint8 fx[16] = {
> src/loaders/stm_load.c:335:                             event->fxt = fx[LSN(b)];
> src/loaders/imf_load.c:132:static const uint8 fx[] = {
> src/loaders/imf_load.c:177:    switch (*fxt = fx[*fxt]) {
> src/loaders/liq_load.c:116:static const uint8 fx[] = {
> src/loaders/liq_load.c:150:    switch (e->fxt = fx[e->fxt]) {
> src/loaders/stx_load.c:118:static const uint8 fx[] = {
> src/loaders/stx_load.c:338:                                     event->fxt = fx[t];
> ```

Do you have any crashers for them?

**Comment by debrouxl** [comment]
Yup, now that I look at it, the AFL++ fuzzing run I had started after reading AliceLR's message in #246 and applying the suggested patch (to reduce the noise) has begun producing stack straces for OOB reads on some of the "fx" arrays listed above:

```
=================================================================
==892121==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f78e65ecf53 at pc 0x7f78e64cc29b bp 0x7ffd3183cf50 sp 0x7ffd3183cf48
READ of size 1 at 0x7f78e65ecf53 thread T0
    #0 0x7f78e64cc29a in xlat_fx .../xmp/libxmp/src/loaders/imf_load.c:177:20
    #1 0x7f78e64c7b0b in imf_load .../xmp/libxmp/src/loaders/imf_load.c:377:3
    #2 0x7f78e64601e4 in load_module .../xmp/libxmp/src/load.c:461:18
    #3 0x7f78e645f60c in xmp_load_module .../xmp/libxmp/src/load.c:606:8
    #4 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #5 0x7f78e5f79cc9 in __libc_start_main csu/../csu/libc-start.c:308:16
    #6 0x420679 in _start (.../bin/xmp+0x420679)

0x7f78e65ecf53 is located 15 bytes to the right of global variable 'fx' defined in 'src/loaders/imf_load.c:132:20' (0x7f78e65ecf20) of size 36
SUMMARY: AddressSanitizer: global-buffer-overflow .../xmp/libxmp/src/loaders/imf_load.c:177:20 in xlat_fx
```

```
==938135==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f68ba74865a at pc 0x7f68ba63484e bp 0x7ffc488c46f0 sp 0x7ffc488c46e8
READ of size 1 at 0x7f68ba74865a thread T0
    #0 0x7f68ba63484d in xlat_fx .../xmp/libxmp/src/loaders/liq_load.c:150:22
    #1 0x7f68ba63484d in liq_load .../xmp/libxmp/src/loaders/liq_load.c:401:6
    #2 0x7f68ba5bb1e4 in load_module .../xmp/libxmp/src/load.c:461:18
    #3 0x7f68ba5ba60c in xmp_load_module .../xmp/libxmp/src/load.c:606:8
    #4 0x4cee43 in main .../xmp/xmp-cli/src/main.c:399:9
    #5 0x7f68ba0d4cc9 in __libc_start_main csu/../csu/libc-start.c:308:16
    #6 0x420679 in _start (.../bin/xmp+0x420679)

0x7f68ba74865a is located 1 bytes to the right of global variable 'fx' defined in 'src/loaders/liq_load.c:116:20' (0x7f68ba748640) of size 25
SUMMARY: AddressSanitizer: global-buffer-overflow .../xmp/libxmp/src/loaders/liq_load.c:150:22 in xlat_fx
```

**Comment by sezero** [comment]
> Yup, now that I look at it, the AFL++ fuzzing run I had started after reading AliceLR's message in #246 and applying the suggested patch (to reduce the noise) has begun producing stack straces for OOB reads on some of the "fx" arrays listed above:
> [...]

Please document them in a new bug entry.

**Comment by AliceLR** [comment]
Going down the list of other loaders that use `fx[]`:

* 669/`669_load.c`: array is the same size as the bound.
* Farandole Composer/`far_load.c`: effect index is inherently bounded within the array size as it comes from `MSN()`.
* Imago Orpheus/`imf_load.c`: definitely affected, as demonstrated above.
* Liquid Tracker/`liq_load.c`: definitely affected, as demonstrated above.
* Liquid Tracker NO/`no_load.c`: array is the same size as the bound (though it's handled in an obfuscated way...).
* Oktalyzer/`okt_load.c`: array is the same size as the bound.
* STM/`stm_load.c`: effect index is inherently bounded within the array size as it comes from `LSN()`.
* STMIX/`stx_load.c`: array is the same size as the bound.
* S3M/`s3m_load.c`: array is the same size as the bound.

IMO all of these should probably have explicit sizes on their arrays. It might also be useful to add an `ARRAY_SIZE` macro so the bounding is based directly on the array and not a magic number elsewhere in the loader.

**Pull request merged**
