### PR TITLE
Fix several OctaMED bugs.

### PR DESCRIPTION
**Pull request by AliceLR**
This fixes several bugs I found while getting a list of modules for #600. cool format

* MMD2/3 16-bit samples were being rejected with an error despite being supported in the common sample loader. This is because a) the check for 16-bit samples was broken and 2) 16-bit samples sometimes have an extra bit set that was associated with early MMD2 16-bit sample support that relied on Aura, so they would have been rejected anyway.
* I also removed the extra check preventing stereo samples from reaching the common loader. These are still broken.
* The MMD2+ `InstrExt` repeat fields were not being loaded. This slightly affected some of the sample repeats in the current MMD3 test module, and presumably was much worse for other modules that rely on samples >128k long. I don't have any specific examples of severe breakage caused by this.
* The MMD2+ `InstrExt` default pitch field was being applied to transpose, which broke [C0ntax/bumble.mmd3](https://ftp.modland.com/pub/modules/OctaMED%20MMD3/C0ntax/bumble.mmd3) from Modland. According to the [OctaMED V5.0 manual](https://web.archive.org/web/20220809231517/https://retro-commodore.eu/files/downloads/amigamanuals-xiik.net/Applications/Octamed%205%20-%20Manual-ENG.pdf) this feature configures the note placed when a note is entered with the F key, and is intended for percussion. There is no indication anywhere in the manual or format document that this affects transpose. This was added here: https://github.com/libxmp/libxmp/commit/deac5227412fd81ab206622823f8cb3a04176027. The [cited module](https://ftp.modland.com/pub/modules/OctaMED%20MMD2/-%20unknown/amience.mmd2) does not have a default pitch field set for any sample and it plays fine with this patch.

edit: more bugs fixed.

* The MMD2+ `InstrExt` instrument flags field was not being applied, which resulted in some MMD2 and MMD3 modules having sample loops enabled/disabled when they shouldn't have been, missing bidirectional loop support, and potentially "disabled" instruments playing when they shouldn't.
* Moved some more repetitive sample loading code to mmd_common.c.

edit: even more bugs fixed.

* Hybrid instruments now properly load their waveforms instead of just loading their sample.
* MMD3 mix mode transpose has been moved to the subinstrument `xpo` field and is now only applied to samples/octave instruments/hybrid instruments. This fixes a bug where regular (non-hybrid) synth instruments would be transposed down two octaves in MMD3 modules.

edit: last batch of bugs fixed in this patch.

* MMD2s and MMD3s with octave samples can now be loaded.
* Added support for ExtSamples.

edit: yet another one.

* Increased the scan pattern row limit for OctaMED modules to 3200, the maximum number of rows allowed in a single block in Amiga OctaMED. defiance.crybaby.5 by Orpheus has three blocks with >=2048 rows.

~~Draft until I find (or make) a suitably small and obvious 16-bit sample test case.~~

### CODE REVIEW

**Comment by AliceLR** [comment]
> This slightly affected some of the sample repeats in the current MMD3 test module, and presumably was much worse for other modules that rely on samples >128k long. I don't have any specific examples of severe breakage caused by this.

There aren't very many that rely on >128k samples, and the ones that also use 16-bit samples are huge :(
```
- unknown/tunnel.mmd3
Chroust/new rein (remix).mmd3
Dominator/brain system collapse.mmd3
Echo/lower lip weird fashion beard.mmd3
Echo/morphine fork no. 7.mmd3
Echo/the seven spoons of intoxication.mmd3
Essential Sound/electra dream.mmd3
Immortal/tomorrow.mmd3
Mark Harman/highland scapes.mmd3
Orpheus/crybaby 5.mmd3
Sniper/dune 3 - stereo oddity.mmd3
Teo.P3/smokin' penguin.mmd3
TTX/video 4.mmd3
TTX/w.s.t.f.song.mmd3
```

**Comment by AliceLR** [comment]
There's also a flags field in `InstrExt` that libxmp is ignoring which needs to be fixed. Not only this, but the `InstrExt` junk also needs to apply to hybrids and IFF#OCT samples. Another patch for this patch incoming. :(

**Comment by AliceLR** [comment]
While I'm here and testing this stuff: I've confirmed hybrids support having waveforms like basically every piece of documentation implies. libxmp loads ONLY the sample right now. This is an easy fix, so I'll go ahead and throw it in.

The editor interface also unfortunately implies they support IFF samples as their sample, which is not an easy fix, but I kind of doubt anything relies on it.

**Comment by sezero** [comment]
Is this still a draft?

**Comment by AliceLR** [comment]
> Is this still a draft?

It's pretty much done, but I want to do some more testing on real modules to make sure I didn't break anything. I'll mark it ready for review later tonight or tomorrow.

**Comment by AliceLR** [comment]
Finally got through enough of these I feel OK with this. It turns out a lot of MMD3s rely on stereo samples and multiple command pages, and some of the synth commands aren't implemented right, so I only tested a few modules for some of the fixes. Other features had few or no examples on Modland to test.

### Long repeat for very long samples (MMD2 and MMD3)

Excluding modules with unused loop parameters (loop off or start past end).

| Module | Test |
|--------|------|
| - unknown/tunnel.mmd3				| OK
| Chroust/new rein (remix).mmd3			| OK
| Echo/morphine fork no. 7.mmd3			| OK
| Echo/the seven spoons of intoxication.mmd3	| OK
| Essential Sound/electra dream.mmd3		| "OK" (stereo sample, module breaks due to 2 command pages)
| Immortal/tomorrow.mmd3			| OK
| Mark Harman/highland scapes.mmd3		| OK
| Orpheus/crybaby 5.mmd3			| OK (broke due 2000+ row blocks, fixed)
| Sniper/dune 3 - stereo oddity.mmd3		| OK
| Teo.P3/smokin' penguin.mmd3			| "OK" (loads OK but the module doesn't even use it)
| TTX/video 4.mmd3				| OK
| TTX/w.s.t.f.song.mmd3				| "OK" (loads OK but the module doesn't even use it)


### Bidirectional loops (MMD2 and MMD3)

1 MMD2 (unused), 153 MMD3s; these pretty much just need to load correctly and have the right flag.

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK
| Chroust/new rein (remix).mmd3			| OK
| Echo/morphine fork no. 7.mmd3			| OK
| Immortal/tomorrow.mmd3			| OK
| Orpheus/crybaby 5.mmd3			| OK
| Teo.P3/smokin' penguin.mmd3			| OK


### Disabled instruments (MMD2 and MMD3)

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK


### 16-bit samples (any format)

1 MMD1 (corrupt?), 161 MMD3s; these pretty much just need to load correctly and have the right flag.

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK
| Essential Sound/electra dream.mmd3		| "OK" (other issues, see long repeat)
| Immortal/tomorrow.mmd3			| OK
| Orpheus/crybaby 5.mmd3			| OK
| Teo.P3/smokin' penguin.mmd3			| OK
| TTX/video 4.mmd3				| OK
| TTX/w.s.t.f.song.mmd3				| OK


### Synth instrument transpose bug (MMD3)

41 MMD3s; only checked a few that use more than one synth instrument.

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK
| DJ Nick/warp.mmd3				| "OK" (3!! command pages, didn't bother listening to the whole thing)
| Essential Sound/system of synth sound.mmd3	| "OK" (issues due to command pages)
| Mortal Tindl/synthese.mmd3			| OK
| Mr. Dig/tocupa.mmd3				| "OK" (issues due to incorrect handling of waveform CHU/CHD commands)
| Seven Eleven/moods-yeah.mmd3			| OK


### Hybrid instruments with waveforms (any format)

MMD0: 51 total, 1 with >1 waveforms
MMD1: 96 total, 0 with >1 waveforms
MMD2: 1 total, 0 with >1 waveforms
MMD3: 7 total, 0 with >1 waveforms

Kind of surprised no one used this, considering you get volume/vibrato envelopes
and can do things like attack transient samples followed by wavetable or PWM waveform cycling.

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK
| Alan Mackey/mb-music 07.mmd0			| Instrument 5 has an unused volume envelope waveform :(


### Octave instruments (MMD2 and MMD3)

1 MMD2, 1 MMD3

| Module | Test |
|--------|------|
| instruments.mmd3 (libxmp test module)		| OK
| Les Hewitt/silly.mmd2				| OK
| The Highlander/hard.mmd3			| OK


### ExtSamples (any format)

1 MMD1, 1 MMD2, 1 MMD3

| Module | Test |
|--------|------|
| extsample.mmd2 (libxmp test module)		| OK
| instruments.mmd3 (libxmp test module)		| OK
| ADR Design/acid filter.mmd1			| OK
| - unknown/salthav.mmd2			| OK (mostly MIDI)
| Dr. Fiss/command & conquer megamix.mmd3	| OK

**Review by sezero — APPROVED** [review]

**Pull request merged**
