### PR TITLE
move dead code under 'bitrot' directory.

### PR DESCRIPTION
**Pull request by sezero**
@cmatsuoka or @AliceLR: can you review?

### CODE REVIEW

**Review by AliceLR — APPROVED** [review]
Some loaders that are already MIT and should maybe be considered "near functional":

* The X-Tracker loader (`dmf_load.c`) was originally enabled but was taken out due to unresolved crash bugs. It has accuracy issues as well, but at one point apparently kind of worked.
* Graomf Tracker loader (`gtk_load.c`) has a similar story to X-Tracker IIRC.
* Desktop Tracker loader (`dtt_load.c`) is pretty readily fixable and I have a partially working bugfix patch. This stalled due to license issues re: the decompression routine and more important IT/Symphony issues that came up. Not hard to pick up again, but not a priority for 4.5.1...

I can really just rebase that patch or whatever, I just thought these ones were worth noting.

**Comment by sezero** [comment]
>    Desktop Tracker loader (`dtt_load.c`) is pretty readily fixable and I have a partially working bugfix patch. This stalled due to license issues re: the decompression routine and more important IT/Symphony issues that came up. Not hard to pick up again, but not a priority for 4.5.1...
> 
> 
> I can really just rebase that patch or whatever, I just thought these ones were worth noting.

If you have a working patch I can leave it out. Or, I can push this and you can pick it back. Which one is your preference?

**Comment by AliceLR** [comment]
Go ahead and push this as-is.

**Comment by sezero** [comment]
OK then.

**Pull request merged**
