### PR TITLE
Close and unlink temporary files in the tests

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by sezero** [comment]
We should do something like the following to silence MS Visual Studio (not tested)
```diff
diff --git a/test-dev/test.h b/test-dev/test.h
index 5851ff4..45edc09 100644
--- a/test-dev/test.h
+++ b/test-dev/test.h
@@ -13,6 +13,9 @@
 #define END_TEST \
 	return 0; }
 
+#ifdef _MSC_VER
+#define unlink _unlink
+#endif
 #ifdef _WIN32
 /* exit() prevents the failure message from being printed! */
 #define FAIL_MSG "**fail**\n"
```

Here is the warning message (from the travis test run):
```
test_write_file_32bit_little_endian.c(20): warning C4996: '_unlink': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _unlink. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdio.h(374): note: see declaration of '_unlink'
```

**Comment by AliceLR** [comment]
> We should do something like the following to silence MS Visual Studio (not tested)

This doesn't fix the warning on my end. This define is also already done in `src/common.h`, which `test.h` includes.

**Comment by sezero** [comment]
> > We should do something like the following to silence MS Visual Studio (not tested)
> 
> This doesn't fix the warning on my end. This define is also already done in `src/common.h`, which `test.h` includes.

Ah, then we should move the `<unistd.h>` includes (and possibly other
system libc includes) before all else.

**Comment by AliceLR** [comment]
> Ah, then we should move the `<unistd.h>` includes (and possibly other
> system libc includes) before all else.

I can confirm that putting the `unistd.h` includes before the `test.h` includes does fix it.

**Comment by sezero** [comment]
@ccawley2011: please move the libc includes before libxmp-specific includes.

**Comment by sezero** [comment]
OR, we can drop all individual unistd.h includes and include it from within test.h?
```diff
diff --git a/test-dev/test.h b/test-dev/test.h
index 5851ff4..333a312 100644
--- a/test-dev/test.h
+++ b/test-dev/test.h
@@ -1,5 +1,6 @@
 #include <xmp.h>
 
+#include <unistd.h>	/* unlink() */
 #include "../src/common.h"
 #include "../src/md5.h"
 
```

**Comment by ccawley2011** [comment]
> OR, we can drop all individual unistd.h includes and include it from within test.h?

OK, done.

**Review by AliceLR — APPROVED** [review]
I've confirmed that all of the MSVC warnings related to `unlink` are fixed (and the global `unistd.h` include doesn't seem to have significantly impacted MinGW build times, if at all). This looks good to me.

**Pull request merged**
