### PR TITLE
ci: port tests from travis to github actions

### PR DESCRIPTION
**Pull request by cmatsuoka**
Add Windows, Linux and MacOS regression tests to GH Actions
and disable Travis.

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Comment by cmatsuoka** [comment]
@AliceLR Also added Windows/msys2 tests, but linking of test binaries is failing. Do you know how to solve this problem?
```
  make check
  shell: D:\a\_temp\msys\msys2.CMD {0}
  env:
    MSYSTEM: MINGW32
CC test/test.o
CC src/md5.o
LD test/libxmp-test
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lxmp
collect2: error: ld returned 1 exit status
make: *** [test/Makefile:23: test/libxmp-test] Error 1
Error: Process completed with exit code 2.
```

**Comment by AliceLR** [comment]
This happens in my local libxmp repo too and I think it's because `LD_LIBRARY_PATH` does not work in MSYS2. Either copying libxmp.dll to test-dev (never tried) or running `make install` as part of the library build (this is how I usually work around it) should fix it.

**Comment by cmatsuoka** [comment]
Thanks, I'll try one of those solutions. Also it seems that it's building libxmp.so.4, unix-style, instead of libxmp.dll (presumably because `_WIN32` is not defined). Is that expected in the msys2 build?

**Comment by AliceLR** [comment]
> Thanks, I'll try one of those solutions. Also it seems that it's building libxmp.so.4, unix-style, instead of libxmp.dll (presumably because `_WIN32` is not defined). Is that expected in the msys2 build?

I've never seen this happen. It always builds `libxmp.dll` and `libdmp.dll.a` for me.

**Comment by cmatsuoka** [comment]
> I've never seen this happen. It always builds `libxmp.dll` and `libdmp.dll.a` for me.
>
> edit: when it installs GCC, is it installing the package `gcc` (MSYS2/Cygwin) or the packages `mingw-w64-x86_64-gcc` (MINGW64) and `mingw-w64-i686-gcc` (MINGW32)?

Aha. I think it's going the Cygwin way, I'll change the package name.

**Comment by AliceLR** [comment]
That seems to have fixed it. This looks good to me—the only tests from Travis-CI missing here are the sanitizer tests. (I have actions for those working in #392.)

**Comment by cmatsuoka** [comment]
Great, if you +1 this one we can land them and disable Travis integration.

**Review by AliceLR — APPROVED** [review]

**Comment by AliceLR** [comment]
Done. Not sure how @sezero has been bypassing the Travis checks to merge, though.

**Comment by cmatsuoka** [comment]
I think I can force-merge the PRs. (And I just realized that I used a commit message convention from a different project I'm working on, hopefully nobody will notice)

**Pull request merged**
