### PR TITLE
build: add experimental travis windows build

### PR DESCRIPTION
**Pull request by cmatsuoka**
Experimental Windows build on Travis. Documentation is a bit scarce, so
this was written on a trial-and-error basis. Variable substitution and directory
separator slashes/backslashes doesn't seem to work like in regular bash.

Clang sanitizer builds disabled because they failed consistently.

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Comment by sezero** [comment]
Can you also add sanitizer checks back, so that this closes #109 and #110?

**Comment by cmatsuoka** [comment]
Windows builds working for 32 and 64 bit. Only the quick test is executed, ideally we should add the full set of regression tests but the testing harness must be ported to windows first.

**Review by sezero — COMMENTED** [review]
The sanitizer checks are commented oft because of clang linkage issue?
It works now since #229 is merged.

lite/Makefile.vc.in needs updating too, for symmetry.

**Comment by cmatsuoka** [comment]
Thanks, I'll merge master and fix the lite Makefile.

**Review by sezero — APPROVED** [review]
OK

**Pull request merged**
