### PR TITLE
make hio_open_file() fail if get_size() returns negative

### PR DESCRIPTION
**Pull request by sezero**
Closes: https://github.com/libxmp/libxmp/issues/338

### CODE REVIEW

**Comment by sezero** [comment]
What are these codecov failure thingies? @AliceLR, @cmatsuoka?

**Comment by sezero** [comment]
> As a workaround would it be possible to add a test to make sure `hio_open_file` fails when given e.g. stdin? (Not sure how portable of a test that would be.)

If you have a patch, feel free to push to my branch :)

**Comment by cmatsuoka** [comment]
I added a basic codecov configuration file in PR #340, could you try to cherry-pick that commit to see if it solves this issue or further tweaking is needed (we could force-merge this one but it would be much better if we could configure codecov properly.)

**Comment by sezero** [comment]
Cherry-picked it, codecov didn't fail this time.

Awaiting reviews of the PR.

**Review by cmatsuoka — COMMENTED** [review]
Thanks Ozkan, that looks good. Could you add some unit testing for that?

**Comment by sezero** [comment]
>  Could you add some unit testing for that?

I don't know how, for now.  @AliceLR had an idea for it: I'm waiting for her to push to this branch.

**Comment by AliceLR** [comment]
I added a test for this but I'm not 100% sure it's portable. Trying to fseek stdin in MinGW has inconsistent results so this test doesn't do anything for Windows builds.

**Review by AliceLR — APPROVED** [review]
The changes unrelated to the test I added look good to me. Someone else might want to give my test a quick look.

**Comment by sezero** [comment]
Test passes on my linux. Nothing to do on mingw if it fails there.
Will merge this as soon as travis completes.

**Pull request merged**
