### PR TITLE
vorbis depacker: respect stb_vorbis_get_frame_float() error returns

### PR DESCRIPTION
**Pull request by sezero**
Fixes: https://github.com/libxmp/libxmp/issues/434

### CODE REVIEW

**Review by AliceLR — APPROVED** [review]
This looks OK. Do you want to upstream this patch or should I?

**Comment by sezero** [comment]
> This looks OK. Do you want to upstream this patch or should I?

You do - provided that `stb_vorbis_get_frame_float` error return is upstreamed too

**Comment by AliceLR** [comment]
On further review, I'm not 100% sure libxmp returning -1 from `stb_vorbis_get_frame_float` is correct: the `error()` usage in that function that exists upstream returns 0, so 0 seems to be the intended return value in an error state. The warnings/potential errors may be our fault because we're using the wrong error return value.

**Comment by sezero** [comment]
However, `stb_vorbis_get_frame_float` does return 0 without actually meaning error in there, am I wrong?

**Comment by AliceLR** [comment]
That's correct, it may be able to return 0 through normal behavior. The only place where it explicitly returns 0 is when `vorbis_decode_packet` fails. This seems to result from either an error case in `vorbis_decode_packet_rest` or when `vorbis_decode_initial` detects an error state and rejects the packet. The latter appears to be in line with the Vorbis I spec, which I've been trying to make sense of: https://xiph.org/vorbis/doc/Vorbis_I_spec.html#x1-730004.3.1

My take on this is that if the explicit error state in the spec only results in rejection of the packet and if returning 0 results in this, that might be good enough. I'm going to try to figure out more about what's going on here, since those two error returns in `stb_vorbis_get_frame_float` are among the error checks I haven't submitted an upstream patch for yet because *I can't prove to myself whether or not they currently do anything meaningful*.

**Pull request merged**
