### PR TITLE
VORBIS.C: Fix typo

### PR DESCRIPTION
**Pull request by raziel-**
Just a tiny typo fixed

Sorry for the noise

### CODE REVIEW

**Comment by sezero** [comment]
This should go to stb mainstream.

**Comment by raziel-** [comment]
Sorry, did i target the wrong file...or repository?

**Comment by sezero** [comment]
The file is correct, but we inherit it from https://github.com/nothings/stb (with modifications, of course, but all submitted mainstream.) You should submit your patch to https://github.com/nothings/stb (against https://github.com/nothings/stb/blob/master/stb_vorbis.c) first. We may then inherit it. Besides, the typo fix is in the changelog, not even in a code comment, that's why I didn't consider its inclusion immediately here.

**Comment by raziel-** [comment]
Understood, didn't know that.

Sorry for the noise

**Pull request closed without merging**
