### PR TITLE
loaders: fix loading xm instruments with more than 16 samples

### LINKED ISSUE #168: Can't play grass.near.the.house.xm
Player refuses to play grass near the house module.
[grass near the house.zip](https://github.com/cmatsuoka/libxmp/files/4666467/grass.near.the.house.zip)

### PR DESCRIPTION
**Pull request by cmatsuoka**
The FT2 specs state that the limit of samples per instrument is 16,
however there are XM modules that exceed this limit (for example,
grass near the house.xm has an instrument with 23 samples). Increase
the limit to 32 to cover these cases, but if a larger number is
found we should handle this in a more dynamic way.

Also improve debug messages in the xm loader.

Fixes #168

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Review by sezero — APPROVED** [review]
This is OK by me. Builds and passes test-dev.

**Comment by sezero** [comment]
And let's see how many hours will take travis to start+complete _and_ whether it signals its result..

**Comment by cmatsuoka** [comment]
Hmm, the tests shouldn't take this long to complete, maybe something is wrong. I'll check.

**Comment by cmatsuoka** [comment]
The average time to complete is around 12min, and Travis is not responsive. It should have timed out already. These PRs are not critical so let's wait a bit more to see if they fix it on their side.

**Comment by sezero** [comment]
> Hmm, the tests shouldn't take this long to complete, maybe something is wrong. I'll check.

Click this: https://github.com/libxmp/libxmp/commit/c54be77b93ffb2c1e40c436d0d96c31b6815db12
See the yellow dot saying that travis is not complete, click details,
see that all checks actually succeeded.

**Comment by cmatsuoka** [comment]
Travis is working, but it's very, very slow for some reason. Since this one is green I'll merge it.

**Pull request merged**
