### PR TITLE
Integrate the OXM depacker with the XM loader

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Review by sezero — APPROVED** [review]
This is a good thing. (And I took the liberty of rebasing it.)

Have you also tested on a big endian host? (see the byte swap
on big endian host in old oxm.c)

**Comment by AliceLR** [comment]
The changes *not* related to xm_load.c look good/trivial, I will review xm_load.c soon.

Some future things that can be separate patch(es):
* The fuzzer tests will need cleanup since they were picked to cover code that no longer exists.
* For various reasons, it might be nice to allow compile time selection between stb_vorbis, libvorbis, Tremor, Tremor-lowmem (some SDKs still use it...), and disabled Vorbis support.

**Comment by sezero** [comment]
>    For various reasons, it might be nice to allow compile time selection between stb_vorbis, libvorbis, Tremor, Tremor-lowmem (some SDKs still use it...), and disabled Vorbis support.

This would be really nice, yes.

And as for tremor, we can even keep a local copy if we want to. And the
lowmem branch would be nice (see my fork of tremor and its lowmem branch
at https://github.com/sezero/tremor/commits/sezero-lowmem where I
did several cleanups.)

**Comment by AliceLR** [comment]
> Have you also tested on a big endian host? (see the byte swap on big endian host in old oxm.c)

What I *remember* finding (still need to verify) is that this byte swap existed because stb_vorbis outputs native endian samples and libxmp wanted to output little endian samples as specified by the XM file format (because libxmp was writing a temporary XM to disk rather than properly loading it).

The XM loader probably just needs to provide a big endian flag to the sample loader after OGG decoding on big endian machines.

**Comment by sezero** [comment]
> The XM loader probably just needs to provide a big endian flag to the sample loader after OGG decoding on big endian machines.

@ccawley2011 seems to have done that (see the `WORDS_BIGENDIAN` ifdef)
What I am not sure about is if that ifdef is correct, whether or not we
need the endian byte swap in test_depack_vorbis.c.

**Comment by AliceLR** [comment]
> What I am not sure about is if that ifdef is correct, whether or not we need the endian byte swap in test_depack_vorbis.c.

Oh. The `test_depack_vorbis.c` byte swap shouldn't be affected by this patch—it's converting the little endian input file to host endian so the test can directly compare samples.

**Comment by sezero** [comment]
> > What I am not sure about is if that ifdef is correct, whether or not we need the endian byte swap in test_depack_vorbis.c.
> 
> Oh. The `test_depack_vorbis.c` byte swap shouldn't be affected by this patch—it's converting the little endian input file to host endian so the test can directly compare samples.

Doh - apparently I didn't look closely.

**Review by AliceLR — APPROVED** [review]
This looks good to me.

Mostly irrelevant, but I wonder if there's any point for the 8-bit conversion loop in `oggdec`...?

**Pull request merged**
