### PR TITLE
build: use configure flag to disable depackers

### PR DESCRIPTION
**Pull request by cmatsuoka**
Use a flag to the configure script to enable and disable depackers
instead of editing the variable directly on the makefile in systems
where the Makefile is generated using autoconf.

OS/2 and VC++ makefiles retain USE_DEPACKERS.

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Comment by sezero** [comment]
This is good (I was lazy to do it this way.)

**Comment by cmatsuoka** [comment]
Thanks for verifying it, could you mark it as approved or make any additional comments (in the "Files changed" tab above, and then "Review changes")?

I'm also fixing the CI tests in PR #202 so after that lands we can merge master into this PR so it can also be ready to be merged.

**Review by sezero — APPROVED** [review]
OK

**Comment by sezero** [comment]
Out of curiosity: Why is 'Rebase and merge' option not enabled?

**Comment by cmatsuoka** [comment]
It's just to make it more visible which set of commits came from each PR (and then you can see all the PR merges with `git log --first-parent`). If all PRs are stacked on top of each other in a linear way you can't do that.

**Comment by sezero** [comment]
This can be merged now, no?

**Comment by sezero** [comment]
PR #202 is done, and something is wrong with travis (takes eons to start -- or finalize?)
Manually merging this one so that we can go on.

**Pull request merged**
