### PR TITLE
Change lha depacker to use a stripped down / modified version of lhasa.

### PR DESCRIPTION
**Pull request by sezero**
With this, the last bit of LGPL code is gone.

The ubsan failures reported to mainstream as https://github.com/fragglet/lhasa/issues/49

Reference issue: https://github.com/libxmp/libxmp/issues/663
Reference issue: https://github.com/libxmp/libxmp/issues/387

### CODE REVIEW

**Comment by sezero** [comment]
Pushed bd8ba6e to fix UBSan errors peek_bits() until mainstream fixes it
in a better way.

Please review, and feel free to push to my branch if necessary .

**Comment by AliceLR** [comment]
Okay, that was shorter than I thought and it *seems* like it should be able to read block-wise from a stream. Dynamically growing the buffer is a problem on our end, then. Do you want to deal with it now (see unxz.c) or wait for slow load files?

I'm getting several crashes in tests locally for some reason (MSYS2/MinGW64), trying to figure out why right now...

**Comment by sezero** [comment]
> WOW this is a lot. I'm going to skip reviewing the lhasa-specific files and let libFuzzer sort that out for us :)

OK :)

> Everything but unlha.c looks good, I need some time to check unlha.c though. A general concern—did you see anything that looks like lhasa dynamically resizing the output buffer, or does it try to allocate the whole output buffer in one go? If the latter, that's going to be a problem.

I'm not sure that I understand the question. We allocate the output buffer by ourselves in unlha.c and pass it to lhasa (to `lha_reader_read()`) along with its size, and it doesn't ever resize our buffer but only write to it (see `lha_decoder_read()`). Does that address the concern or am I missing anything?

**Comment by AliceLR** [comment]
> I'm not sure that I understand the question. We allocate the output buffer by ourselves in unlha.c and pass it to lhasa (to `lha_reader_read()`) along with its size, and it doesn't ever resize our buffer but only write to it (see `lha_decoder_read()`). Does that address the concern or am I missing anything?

Yes, this is what I meant—I hadn't looked at unlha.c yet. This can cause slow enough loads with some depackers (bunzip2.c, unxz.c) that I've had to change them to resize the buffer by powers of 2 instead of allocating them with a single call—this is a lot faster for invalid files and thus libFuzzer.

**Comment by sezero** [comment]
> I don't think it's a big enough deal to block this, I can just patch it in later.

OK, as you wish

**Review by AliceLR — APPROVED** [review]
OK, let's get this in already...

**Comment by sezero** [comment]
Note that this adds `mktime` among the libc calls used, which we haven't
used before: It calls it when decoding timestamps. We don't really need
the timestamps and I first wanted to remove all timestamp decoding & etc
but macbinary.c depends on a timestamp comparison, so I kept them as is.
Not anything serious at all, but just wanted to note...

**Comment by sezero** [comment]
>  skip reviewing the lhasa-specific files and let libFuzzer sort that out for us :)

Any news from fuzzing?

**Comment by AliceLR** [comment]
> Any news from fuzzing?

So far, nothing. No ASan crashes yet, and the only slow loads and timeouts have all been caused by the stb_vorbis `qsort` (already reported upstream).

**Comment by sezero** [comment]
That's great!

**Pull request merged**
