### PR TITLE
Remove remaining uses of absolute include paths

### PR DESCRIPTION
**Pull request by Clownacy**
Extending some work from #419 to the rest of libxmp. The idea behind using relative paths only is so that other projects can use libxmp's source files directly and they'll 'just work' without requiring that the `src` directory be force-included.

### CODE REVIEW

**Comment by sezero** [comment]
This looks OK tome, but the second part of the patch misses four files:
```diff
diff --git a/lite/Makefile.vc.in b/lite/Makefile.vc.in
index 52877f6..411bc70 100644
--- a/lite/Makefile.vc.in
+++ b/lite/Makefile.vc.in
@@ -3,7 +3,7 @@
 #
 
 CC	= cl
-CFLAGS	= /O2 /W3 /MD /Iinclude\libxmp-lite /Isrc /DBUILDING_DLL /DWIN32 \
+CFLAGS	= /O2 /W3 /MD /Iinclude\libxmp-lite /DBUILDING_DLL /DWIN32 \
           /Dinline=__inline /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS /DLIBXMP_CORE_PLAYER /DLIBXMP_NO_PROWIZARD /DLIBXMP_NO_DEPACKERS
 LD	= link
 LDFLAGS	= /DLL /RELEASE /OUT:$(DLL)
diff --git a/lite/watcom.mif.in b/lite/watcom.mif.in
index 26ade67..0f9fd5d 100644
--- a/lite/watcom.mif.in
+++ b/lite/watcom.mif.in
@@ -1,6 +1,6 @@
 CFLAGS += -DHAVE_ALLOCA_H -DHAVE_FNMATCH -DHAVE_MKSTEMP -DHAVE_UMASK -DLIBXMP_CORE_PLAYER -DLIBXMP_NO_PROWIZARD -DLIBXMP_NO_DEPACKERS
 #CFLAGS += -DDEBUG
-CFLAGS += -I"include/libxmp-lite" -Isrc
+CFLAGS += -I"include/libxmp-lite"
 
 DLLFLAGS=-bd -DBUILDING_DLL
 STATICFLAGS=-DBUILDING_STATIC
diff --git a/watcom.mif b/watcom.mif
index cc9c45c..42ecf16 100644
--- a/watcom.mif
+++ b/watcom.mif
@@ -6,7 +6,7 @@ CFLAGS += -DLIBXMP_NO_DEPACKERS
 !endif
 CFLAGS += -DHAVE_ALLOCA_H -DHAVE_FNMATCH -DHAVE_MKSTEMP -DHAVE_UMASK
 #CFLAGS += -DDEBUG
-CFLAGS += -Iinclude -Isrc
+CFLAGS += -Iinclude
 
 DLLFLAGS=-bd -DBUILDING_DLL
 STATICFLAGS=-DBUILDING_STATIC
diff --git a/watcom.mif.in b/watcom.mif.in
index 24691ee..560e7f6 100644
--- a/watcom.mif.in
+++ b/watcom.mif.in
@@ -6,7 +6,7 @@ CFLAGS += -DLIBXMP_NO_DEPACKERS
 !endif
 CFLAGS += -DHAVE_ALLOCA_H -DHAVE_FNMATCH -DHAVE_MKSTEMP -DHAVE_UMASK
 #CFLAGS += -DDEBUG
-CFLAGS += -Iinclude -Isrc
+CFLAGS += -Iinclude
 
 DLLFLAGS=-bd -DBUILDING_DLL
 STATICFLAGS=-DBUILDING_STATIC
```

**Comment by sezero** [comment]
@AliceLR:  OK with you?

**Comment by Clownacy** [comment]
> This looks OK to me, but the second part of the patch misses four files:

Whoops, thanks.

**Review by sezero — APPROVED** [review]

**Review by AliceLR — APPROVED** [review]
This looks good to me. Thanks for cleaning these up. Using `-Isrc/` seems like a good way to break system headers in hard to diagnose ways...

**Pull request merged**
