### PR TITLE
github/workflows: add distribution package test

### PR DESCRIPTION
**Pull request by cmatsuoka**
Add a github action to build regular and lite distribution packages and
verify if they're correct.

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Comment by cmatsuoka** [comment]
After this test is merged and proven successful we can migrate a few more actions from travis, especially those running on systems that are very slow to start there.

**Comment by sezero** [comment]
I don't know anything about github workflows.  Speaking for myself, if you need an approval I'll add it.

**Comment by cmatsuoka** [comment]
Apparently my test run in my own fork failed to publish artifacts, I'm working to fix it.

**Review by sezero — APPROVED** [review]

**Comment by cmatsuoka** [comment]
Ok, now it worked. I'll merge it and see if it works for future PRs, unfortunately there's no apparent way to test this without merging it first.

**Comment by sezero** [comment]
Pushed a changelog update - let's see how github/workflows work.

**Pull request merged**
