### PR TITLE
Add sample preamplification to filter mixers.

### PR DESCRIPTION
**Pull request by AliceLR**
This is required to correct rounding errors that accumulate when using higher sample rates than libxmp currently allows, making filtered channels with low cutoffs sound distorted. Unfortunately it also messes up all of the mixer tests (again...).

I also increased `FILTER_BITS` to the maximum useful value (~~24~~ 22, since the filter parameters are calculated with single precision floats, and also x87/IEEE-754 rounding differences). This is also necessary for higher sample rates.

This is a prerequisite for fixing #171.

### CODE REVIEW

**Comment by AliceLR** [comment]
Failure looks like cumulative x87 rounding differences due to the expanded precision of the filter calculations. Dropping the precision on the filter parameters to 22 bits or changing the filter calculations to use double precision floats fixes it. Fix incoming (just changing the precision to 22 bits...).

**Comment by sezero** [comment]
is this finalized ?

**Comment by AliceLR** [comment]
> is this finalized ?

??? Yes, I marked it ready for review.

**Comment by sezero** [comment]
OK. @sagamusix , @cmatsuoka : Any objections?

**Review by sagamusix — APPROVED** [review]

**Comment by sezero** [comment]
OK, this is in.

**Pull request merged**
