### PR TITLE
Improve anticlick performance and fix anticlick filter volume bug.

### PR DESCRIPTION
**Pull request by AliceLR**
This fixes two bugs in the anticlick routine found in #400:

* The existing anticlick routine was slow due to relying on repeated integer division and, for large tick sizes, could truncate very large portions of the source sample. It has been replaced by a (much) faster fixed point variant of the same algorithm that outputs a more accurate curve.
* @debrouxl pointed out that the module "The Hero Within" by @sagamusix has click issues and would be worth testing the updated algorithm against. I diagnosed the remaining clicks and found that they're caused by behavior in the filter mixers where the previous sample values would be stored after volume was applied, almost entirely negating the anticlick volume ramp. Volume is now applied after the filter calculation, entirely fixing the popping issue (as far as I can tell) in this module.

I also added some deadcode to the mixer tests to make it easier to regenerate their output.

(edit: probably worth noting that this is still currently being tested against existing modules in the aforementioned issue.)

### CODE REVIEW

**Comment by AliceLR** [comment]
Oops, need to fix the regular test too. Will push in a bit.

**Comment by AliceLR** [comment]
Here's a small set of modules (plus The Hero Within) I've found from my local ModLand copy with noticeable filter usage that may cause clicks in master but doesn't in this branch. It doesn't seem that there are actually that many modules using filters that have that playback issue, maybe because rapid notes with filters tend to use more percussive sounds that mask the click. The Hero Within is still the most obvious one with this problem I've heard so far.

[it_filter_anticlick.zip](https://github.com/libxmp/libxmp/files/6751686/it_filter_anticlick.zip)

**Comment by sezero** [comment]
@cmatsuoka, what's the verdict on this?

**Comment by AliceLR** [comment]
FWIW I don't think merging this needs to be rushed. I'm fairly confident at this point that both of these changes are correct but it's not like e.g. a critical build system bug or vulnerability. (It doesn't help that fixing the mixer tests blew up the size of the diff to >7k lines, despite the actual part of the diff worth reviewing only being a couple dozen at best.)

If you want to cut a release for 4.5.1 I think it would be OK to do that and delay merging this (and further patches for #390, #400, other playback bugs) to 4.5.2. libxmp uses semantic versioning as far as I can tell so there can be as many release versions as we need. :)

**Comment by AliceLR** [comment]
(Nothing new here, just rebased.)

**Comment by debrouxl** [comment]
On my side, the hearing test on ~65 modules by Saga Musix, as well as several other ones, is alright: no noticeable new clicks, or reduction in noticeable clicks outside of The Hero Within.
FWIW, of course: it suffices that the relevant modules don't use the sample / effect / etc. conditions impacted by this change for no impact to be heard...

**Comment by AliceLR** [comment]
I forgot to post it here, but I did manage to reproduce this bug in a custom module, and confirmed this branch does remove the pops here as well: [it_filter_pop.it.zip](https://github.com/libxmp/libxmp/files/6772944/it_filter_pop.it.zip)

**Review by sezero — APPROVED** [review]

**Comment by sezero** [comment]
How much more testing does this one need?

**Comment by debrouxl** [comment]
I haven't listened to my whole usual set of modules, but at this rate, it's going to take a while... and anyway, this hearing test has no value if none of these modules happens to use the sample / effect / note conditions where a change in the anticlick algorithm produces an audible change in output.

**Comment by AliceLR** [comment]
From my testing I was fairly satisfied that this adequately fixed the filter bug without breaking anything, but I don't have a library of ITs I regularly listen to to compare.

**Comment by sezero** [comment]
What to do with this then? @cmatsuoka is unresponsive these days..

**Comment by NoSuck** [comment]
I tried to test these changes, but `make` failed (even after `autoconf && ./configure --prefix=/usr && make clean`):

```
make: *** No rule to make target 'src/xfnmatch.h', needed by 'src/load_helpers.lo'.  Stop.
```

**Comment by sezero** [comment]
You are running with an outdated libxmp source tree

**Comment by AliceLR** [comment]
> I tried to test these changes, but `make` failed (even after `autoconf && ./configure --prefix=/usr && make clean`):
> 
> ```
> make: *** No rule to make target 'src/xfnmatch.h', needed by 'src/load_helpers.lo'.  Stop.
> ```

Try a `make distclean`—I don't think regular `make clean` removes `depend` currently. (xfnmatch was moved to src/depackers/ since it's only used by those.)

**Comment by AliceLR** [comment]
Rebased to master since the `-Wunused-result` fixes conflicted with the mixer data generation deadcode this patch adds.

**Comment by debrouxl** [comment]
FWIW, I've listened to several hundred more files, without hearing ill effects caused by this patch. The same caveats still apply. More modules to listen to...

**Comment by sezero** [comment]
I'm tempted to apply this patch

**Comment by debrouxl** [comment]
No obvious change on 52 modules from Awesome, either.

**Comment by sezero** [comment]
Let's merge this ?

**Comment by sezero** [comment]
PING?

**Comment by debrouxl** [comment]
No objection from me, but I'm not a reviewer anyway.

**Comment by AliceLR** [comment]
I'm fine with merging this. I don't think it's actually a big enough change for us to keep bugging Claudio about it, and all testing so far points to this patch working correctly.

**Comment by sezero** [comment]
OK, merging.

**Pull request merged**
