### PR TITLE
Split vc-prepare source lists onto individual lines for each file.

### PR DESCRIPTION
**Pull request by AliceLR**
See discussion in #470. Every time a source file is added it creates a large and unreadable diff due to every source file being clustered onto a single line. This should fix that problem for the NMake Makefiles.

~~FIXME: this should also be done for the Watcom Makefile but I don't know if it supports the same syntax for escaping line breaks and I don't have an environment to test it with yet.~~ Done.

### CODE REVIEW

**Comment by sezero** [comment]
For watcom, use `&` instead of `\` for line continuation, something like the following works:
```diff
diff --git a/Makefile.in b/Makefile.in
index dd20c08..20e5b9e 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -205,5 +205,5 @@ watcom-prepare:
 	@echo Generate watcom.mif
-	@sed -e 's!@OBJS@!$(OBJS:.o=.obj)!' \
-	     -e 's!@POBJS@!$(PROWIZARD_OBJS:.o=.obj)!' \
-	     -e 's!@DOBJS@!$(DEPACKER_OBJS:.o=.obj)!' \
+	@sed -e 's!@OBJS@! \&\n $(OBJS:.o=.obj \&\n)!' \
+	     -e 's!@POBJS@! \&\n $(PROWIZARD_OBJS:.o=.obj \&\n)!' \
+	     -e 's!@DOBJS@! \&\n $(DEPACKER_OBJS:.o=.obj \&\n)!' \
 	     watcom.mif.in > watcom.mif
```

**Comment by sezero** [comment]
One nit: The last line gets the `\` too in each source definition. The result does work,
but I wonder if we can prevent that.

**Comment by AliceLR** [comment]
> For watcom, use `&` instead of `\` for line continuation, something like the following works:

OK, will update to add that.

> One nit: The last line gets the `\` too in each source definition. The result does work,
> but I wonder if we can prevent that.

I don't really like that either. `$(addprefix)` considered the escapes as separate tokens and prefixed them... I can try to clean that up.

**Comment by AliceLR** [comment]
OK, I've made both requested changes.

**Comment by sezero** [comment]
Is 'not adding a line continuation' to last line not possible, I guess?

**Review by sezero — APPROVED** [review]

**Comment by AliceLR** [comment]
> Is 'not adding a line continuation' to last line not possible, I guess?

I think something could *probably* be hacked together with `shell` or some combination of the few text functions GNU Make provides, but it wouldn't be very nice.

I don't think the trailing `\` will hurt much, though. These lists are automated, so the likelihood of those lines getting removed is minimal, and CI will almost certainly catch it immediately if they are.

**Comment by sezero** [comment]
I tried filtering the first sed result with a second one like
`[...]	     watcom.mif.in | sed -e 's! \&\n\n!\n\n!' > watcom.mif`
but failed.

But no, not a big deal.

**Pull request merged**
