### PR TITLE
Fix tempo assignment in pre-scan loop

### LINKED ISSUE #153: Crash at seek with xyce-dans_la_rue.xm
Another issue with xyce-dans_la_rue.xm - Xmp for Android crashes if i try to seek. Removing E60 command from pattern 0F channel 4 line 20 seems to solve this problem, but i want to know if it can be fixed on xmp side.

### PR DESCRIPTION
**Pull request by cmatsuoka**
Before playing a module we run a pre-scan to get timestamps for
each pattern, among other pieces of information. Update this data
if it's not set, meaning that we don't update e.g. inside a pattern
loop. This should fix seek in xyce-dans_la_rue.xm.
    
Fixes #153
    
Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>

### CODE REVIEW

**Review by sezero — APPROVED** [review]
OK.

**Comment by sezero** [comment]
Does this affect #152 in any way?

**Comment by cmatsuoka** [comment]
> Does this affect #152 in any way?

It doesn't seem to be related, I'm investigating it.

**Review by AliceLR — APPROVED** [review]
This fix looks correct as far as I can tell.

**Pull request merged**
