### PR TITLE
Add MIT-licensed Digital Symphony LZW decoder.

### PR DESCRIPTION
**Pull request by AliceLR**
This removes the Digital Symphony loader's dependency on the LGPL licensed ARC/ArcFS LZW decoder used in the depackers, meaning libxmp builds with --disable-depackers should now be fully MIT. Additionally, the new decoder no longer requires that the provided `HIO_HANDLE *` be backed by a `FILE *`.

This code is adapted from a [GPL UnShrink implementation](https://github.com/AliceLR/megazeux/blob/master/src/io/zip_shrink.h) I wrote from scratch (and can thus relicense... :) ). Some code cleanup is probably needed, as well as more testing. The format test I've added is the *only* module I've tested so far since so many of them have other sample issues (see #347).

- [x] Need to look into the FULLEFFECT / NARCOSIS quirk reported in the aforementioned issue.
- [x] Probably should do some light fuzzing (which can be done now since loading from memory works).
- [x] Additional code, coverage tweaks, or tests as-needed.
- [x] Since all of the sample sizes are known ahead of time, just allocate one intermediate sample buffer in the Digital Symphony loader...

### CODE REVIEW

**Comment by AliceLR** [comment]
Did a full run on APDL for master and for this branch (with a minor bounding fix) and the only difference is `fulleffect.zip`, `narcosis.zip`, and `newdance.zip` now load instead emitting errors. So, I guess that answers whether or not I got that quirk implemented correctly...

**Comment by sezero** [comment]
Builds and works fine so far on my end.

Are the assert()s safe to disable?

**Comment by sezero** [comment]
> Are the assert()s safe to disable?

Evidently not: I took all of the files from https://ftp.modland.com/pub/modules/Digital%20Symphony/
and the following ones gave me:
`xmp: src/loaders/lzw.c:166: LZW_add: Assertion `lzw->bits <= ((lzw->flags) & 15)' failed.`

https://ftp.modland.com/pub/modules/Digital%20Symphony/-%20unknown/is_it_true.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/-%20unknown/witness.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/Entity/only_paradox_part_2.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/George%20Botsford/black_and_white_rag.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/Klim/lsi.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/Martin%20Bazley/forst_at_night.dsym
https://ftp.modland.com/pub/modules/Digital%20Symphony/Raj/puff_the_magic_dragon.dsym

**Comment by sezero** [comment]
And now I can't reproduce it with a fresh checkout: was I using an old version?..

**Comment by AliceLR** [comment]
> > Are the assert()s safe to disable?
> 
> Evidently not: I took all of the files from https://ftp.modland.com/pub/modules/Digital%20Symphony/
> and the following ones gave me:
> `xmp: src/loaders/lzw.c:166: LZW_add: Assertion `lzw->bits <= ((lzw->flags) & 15)' failed.`

Make sure you have commit f11d990 in your local build—that is a bug I fixed prior to my last comment that appeared because I had to change how the code width is incremented.

**Comment by sezero** [comment]
> Make sure you have commit [f11d990](https://github.com/libxmp/libxmp/commit/f11d990a051031ab85972480ddd3a9fcab2abea4) in your local build

Yes, that was the reason

**Comment by sezero** [comment]
Still going good. Improves malloc usage too: The old
`==13247==   total heap usage: 162 allocs, 162 frees, 11,233,684 bytes allocated`
versus:
`==13248==   total heap usage: 138 allocs, 138 frees, 1,145,088 bytes allocated`

One warning when compiling with `-O3`:
```
src/loaders/lzw.c: In function 'libxmp_read_lzw':
src/loaders/lzw.c:276: warning: 'lzw.previous_first_char' may be used uninitialized in this function
```
Initializing it to 0 in `LZW_init_tree` cures it:
```diff
diff --git a/src/loaders/lzw.c b/src/loaders/lzw.c
index 8ce3f0b..2f78bb5 100644
--- a/src/loaders/lzw.c
+++ b/src/loaders/lzw.c
@@ -119,4 +119,5 @@ static int LZW_init_tree(struct LZW_tree *lzw, int flags)
 	lzw->new_inc = 0;
 	lzw->flags = flags;
+	lzw->previous_first_char = 0;
 
 	for (i = 0; i < 256; i++) {
```

**Comment by AliceLR** [comment]
OK, I added that. I don't think an uninitialized use should ever be possible but it costs nothing to fix. (It's set in `LZW_output` and referenced in `LZW_add`; the only time `LZW_add` is called before `LZW_output` is a case guarded by making sure a previous code existed to initialize it).

**Comment by AliceLR** [comment]
Rebased to fix the Makefile.vc/watcom.mif merge conflict.

So far I've fuzzed quite a bit with ASan and UBSan, which have found nothing related to this decoder. Just MSan left (now that I've fixed a bunch of unrelated issues).

**Comment by AliceLR** [comment]
I've done a bit of MSan testing and it found nothing in this decoder (but some other misc. issues elsewhere). I'm going to go ahead and mark this ready to review.

**Comment by AliceLR** [comment]
Nevermind, checked the coverage and it looks like nothing is actually covering tree clearing currently. I need to see if this is even a thing in Digital Symphony's LZW...

**Comment by AliceLR** [comment]
I squashed all of the commits and replaced the format test with a file that 1) uses LZW clears and 2) uses more effects than the previous one. Unfortunately, codecov is now rate limiting me (?) when I try to view the coverage for these files...

**Comment by AliceLR** [comment]
A couple of tweaks pushed:

* codecov reports that the new file does, in fact, cover LZW clears.
* The LZW EOF code seems to be 100% unique to Digital Symphony, so I've tweaked the handling of it to only apply with Digital Symphony quirks enabled.
* The readlzw.c function `libxmp_read_lzw_dynamic` seems to have existed solely for the Digital Symphony loader, so I removed it.

**Review by sezero — APPROVED** [review]
OK, let's apply this.

**Pull request merged**
