### PR TITLE
Testing Travis CI

### PR DESCRIPTION
**Pull request by NoSuck**
Clang doesn't like something.

https://travis-ci.org/cmatsuoka/libxmp/builds/296784287

### CODE REVIEW

**Comment by NoSuck** [comment]
It seems the clang Travis CI check fails when merely adding a comment to a branch that is even with master.  Can anyone shed light on this?

**Comment by AliceLR** [comment]
Looks like the failing check is due to LeakSanitizer. I can take a look at some of its reports when I get a chance.

**Comment by sezero** [comment]
Are there any leak issues left with current master? If not, let's close this one.

**Comment by AliceLR** [comment]
I don't have any leaks when I run LeakSanitizer locally anymore but it might be worth adding the ASan CI checks again to make sure there isn't anything else that needs to be fixed.

**Comment by sezero** [comment]
Fixed finally by #224. Closing.

**Pull request closed without merging**
