### PR TITLE
Fix out-of-bounds reads/writes in ST and MASI loaders, SQSH depacker.

### PR DESCRIPTION
**Pull request by AliceLR**
Fixes the following bugs found in #280:
* The ST .MOD loader test function allows invalid instrument numbers in some cases, but then could use the invalid number to index the instruments array when counting the total file size.
* The MASI PSM loader could get stuck in an infinite loop trying to parse a truncated SONG chunk.
* The MASI PSM loader was missing a sanity check on the maximum number of orders and could overflow the buffer used to store pattern names for the order list.
* The SQSH depacker was completely missing sanity checks while parsing an input bitstream, which could allow it to read beyond the end of the input buffer.

### CODE REVIEW

**Review by sezero — APPROVED** [review]

**Comment by sezero** [comment]
These look good.

However, you need one missing sanity check in unsqsh.c: patch and
a related crasher (once provided by Lionel Debroux) are attached.
[fuzz.zip](https://github.com/libxmp/libxmp/files/5780970/fuzz.zip)
[patch.txt](https://github.com/libxmp/libxmp/files/5780973/patch.txt)

**Comment by sezero** [comment]
Will be applying unsqsh parts of this PR to libmikmod, soon.

**Comment by AliceLR** [comment]
Nice catch; I hadn't got to testing most of the other crashers since I assumed they were mostly ProWizard related. I will apply this patch/test and force push soon.

**Comment by sezero** [comment]
>  this is from a different fuzzing set?

Yes, it was from a set Lionel Debroux sent to me about a year and a half ago for libmikmod.
I was lazy to work on the xpk parts, I now did :)

**Pull request merged**
